# Class_17_21_Nov_Avishay

In [1]:
import numpy as np

In [2]:
#numerical operations

Numpy Arrays 

In [3]:
a = [1,2,3]

In [4]:
var = np.array(a)

In [5]:
var

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
var2 = np.array(my_matrix)

In [9]:
var2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
len(var2)

3

In [11]:
len(var)

3

# Methods

In [14]:
np.arange(0,10)   #from 0 till 10-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11,2)  #2 here is the jump/steps

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(1)

array([0.])

In [22]:
np.zeros(0)


array([], dtype=float64)

In [23]:
np.ones(1)

array([1.])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

linspace

In [29]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [33]:
(np.linspace(0,10,4)).round()   #round removes the decimel

array([ 0.,  3.,  7., 10.])

In [34]:
(np.linspace(0,20,4)).round() 

array([ 0.,  7., 13., 20.])

eye

In [36]:
np.eye(4)    #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.eye(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Random

In [39]:
np.random.rand(2)   #between 0 & 1   #uniform distribution 

array([0.62480803, 0.71656259])

In [42]:
np.random.rand(2,5)

array([[0.36642088, 0.3152382 , 0.47524044, 0.43509213, 0.79572307],
       [0.74813127, 0.35189202, 0.76403469, 0.3641301 , 0.23845182]])

In [43]:
np.random.rand(2)  

array([0.62676968, 0.82114449])

In [44]:
np.random.randint(1,100)

18

In [45]:
np.random.randint(1,100,10)

array([57, 34, 51, 82, 77,  4, 27, 67, 51, 39])

In [46]:
np.random.randint(100,200,10)

array([155, 179, 180, 129, 139, 157, 115, 198, 189, 122])

# Reshape

In [47]:
arr = np.arange(25)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr = np.arange(24)

In [52]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
arr.max()

23

In [56]:
arr.min()

0

In [57]:
arr.argmax()

23

In [58]:
arr.argmin()

0